service: transmitter-smtp-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 256
  environment:
    EMAIL_FROM: ${ssm:/transmitter/service/smtp/email/FROM}
    SMTP_CONFIGURATION: ${ssm:/transmitter/service/smtp/SMTP_CONFIGURATION~true}

plugins:
  - serverless-offline-aws-ssm
  - serverless-offline

package:
  exclude:
    - offline.yml
    - offline.yml.dist
    - .gitignore
    - docker/**
    - package.json
    - package-lock.json
    - serverless.yml

functions:
  http:
    handler: handler/http.app
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'

custom:
  serverless-offline:
    host: 0.0.0.0