service: transmitter-smtp-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 256
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    EMAIL_FROM: ${file(./serverless.vars.${self:provider.stage}.yml):email_from}
    SMTP_CONFIGURATION: ${file(./serverless.vars.${self:provider.stage}.yml):smtp_configuration}

plugins:
  - serverless-offline

package:
  exclude:
    - offline.yml
    - offline.yml.dist
    - .gitignore
    - docker/**
    - package.json
    - package-lock.json
    - serverless.yml

functions:
  http:
    handler: handler/http.app
    events:
      - httpApi:
          method: ANY
          path: /{proxy+}

custom:
  serverless-offline:
    host: 0.0.0.0